In [ ]:
from google.colab import drive
from typing import Dict, Iterator, List, Sequence, Union
import os
import json
import pandas as pd
import numpy as np

In [ ]:
pd.set_option('display.max_columns', None)

### 0. Load Data From Drive

In [ ]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
DATA_DIR = '/content/drive/My Drive/NEU/Graduate/CS_6140/Data/'
SAVE_DATA_DIR = '/content/drive/My Drive/NEU/Graduate/CS_6140/Data/features_data/'
PREPROCESSED_DATA_F = 'preprocessed_data_variable_hour_window_cols.csv'
PREPROCESSED_DATA_LOC = os.path.join(DATA_DIR, PREPROCESSED_DATA_F)

In [ ]:
df = pd.read_csv(
    PREPROCESSED_DATA_LOC,
)
print(f"- {format(len(df), ',')} total rows in df.")
df.head(3)

- 876,100 total rows in df.

,datetime,machineID,volt,rotate,pressure,vibration,12_machineID_time_window,12_order_in_time_window,12_machine_example_ID,12_step_ID,24_machineID_time_window,24_order_in_time_window,24_machine_example_ID,24_step_ID,48_machineID_time_window,48_order_in_time_window,48_machine_example_ID,48_step_ID,72_machineID_time_window,72_order_in_time_window,72_machine_example_ID,72_step_ID,comp1_maint,comp2_maint,comp3_maint,comp4_maint,error1,error2,error3,error4,error5,comp1_failure,comp2_failure,comp3_failure,comp4_failure,age,model2,model3,model4
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686,1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973,1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847,1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False

In [ ]:
df = df[
    [
        'datetime', 'machineID',
        '12_machineID_time_window', '12_order_in_time_window', '12_machine_example_ID', '12_step_ID',
        '24_machineID_time_window', '24_order_in_time_window', '24_machine_example_ID', '24_step_ID',
        '48_machineID_time_window', '48_order_in_time_window', '48_machine_example_ID', '48_step_ID',
        '72_machineID_time_window', '72_order_in_time_window', '72_machine_example_ID', '72_step_ID',
        'age',
        'model2', 'model3', 'model4',
        'volt', 'rotate', 'pressure', 'vibration',
        'comp1_maint', 'comp2_maint', 'comp3_maint', 'comp4_maint',
        'error1', 'error2', 'error3', 'error4', 'error5',
        'comp1_failure', 'comp2_failure', 'comp3_failure', 'comp4_failure',
    ]
]

In [ ]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['machineID'] = df['machineID'].astype(int)

df['12_machineID_time_window'] = df['12_machineID_time_window'].astype(int)
df['12_order_in_time_window'] = df['12_order_in_time_window'].astype(int)
df['12_machine_example_ID'] = df['12_machine_example_ID'].astype(str)
df['12_step_ID'] = df['12_step_ID'].astype(str)
df['24_machineID_time_window'] = df['24_machineID_time_window'].astype(int)
df['24_order_in_time_window'] = df['24_order_in_time_window'].astype(int)
df['24_machine_example_ID'] = df['24_machine_example_ID'].astype(str)
df['24_step_ID'] = df['24_step_ID'].astype(str)
df['48_machineID_time_window'] = df['48_machineID_time_window'].astype(int)
df['48_order_in_time_window'] = df['48_order_in_time_window'].astype(int)
df['48_machine_example_ID'] = df['48_machine_example_ID'].astype(str)
df['48_step_ID'] = df['48_step_ID'].astype(str)
df['72_machineID_time_window'] = df['72_machineID_time_window'].astype(int)
df['72_order_in_time_window'] = df['72_order_in_time_window'].astype(int)
df['72_machine_example_ID'] = df['72_machine_example_ID'].astype(str)
df['72_step_ID'] = df['72_step_ID'].astype(str)

df['age'] = df['age'].astype(int)
df['model2'] = df['model2'].astype(int)
df['model3'] = df['model3'].astype(int)
df['model4'] = df['model4'].astype(int)

df['volt'] = df['volt'].astype(float)
df['rotate'] = df['rotate'].astype(float)
df['pressure'] = df['pressure'].astype(float)
df['vibration'] = df['vibration'].astype(float)
df['comp1_maint'] = df['comp1_maint'].astype(int)
df['comp2_maint'] = df['comp2_maint'].astype(int)
df['comp3_maint'] = df['comp3_maint'].astype(int)
df['comp4_maint'] = df['comp4_maint'].astype(int)
df['error1'] = df['error1'].astype(int)
df['error2'] = df['error2'].astype(int)
df['error3'] = df['error3'].astype(int)
df['error4'] = df['error4'].astype(int)
df['error5'] = df['error5'].astype(int)
df['comp1_failure'] = df['comp1_failure'].astype(int)
df['comp2_failure'] = df['comp2_failure'].astype(int)
df['comp3_failure'] = df['comp3_failure'].astype(int)
df['comp4_failure'] = df['comp4_failure'].astype(int)

### 1. Create One Feature File per Feature Time Window Length

In [ ]:
df.head(4)

,datetime,machineID,12_machineID_time_window,12_order_in_time_window,12_machine_example_ID,12_step_ID,24_machineID_time_window,24_order_in_time_window,24_machine_example_ID,24_step_ID,48_machineID_time_window,48_order_in_time_window,48_machine_example_ID,48_step_ID,72_machineID_time_window,72_order_in_time_window,72_machine_example_ID,72_step_ID,age,model2,model3,model4,volt,rotate,pressure,vibration,comp1_maint,comp2_maint,comp3_maint,comp4_maint,error1,error2,error3,error4,error5,comp1_failure,comp2_failure,comp3_failure,comp4_failure
0,2015-01-01 06:00:00,1,1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",18,0,1,0,176.217853,418.504078,113.077935,45.087686,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2015-01-01 07:00:00,1,1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",18,0,1,0,162.879223,402.747490,95.460525,43.413973,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2015-01-01 08:00:00,1,1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",18,0,1,0,170.989902,527.349825,75.237905,34.178847,0,0,0,0,0,0,0,0,0,0,0,0,0
3,2015-01-01 09:00:00,1,1,4,"(001, 001)","(001, 001, 004)",1,4,"(001, 001)","(001, 001, 004)",1,4,"(001, 001)","(001, 001, 004)",1,4,"(001, 001)","(001, 001, 004)",18,0,1,0,162.462833,346.149335,109.248561,41.122144,0,0,0,0,0,0,0,0,0,0,0,0,0

##### 1.1) Define Helper Functions to Obtain Outcomes

In [ ]:
def chunker(
    seq: Sequence,
    size: int
) -> Iterator[Sequence]:
    """
    Purpose: Splits the sequence into chunks of given size.
    :return: An iterator over chunks of the original sequence.
    """
    return (
        seq[pos : pos+size] for pos in range(0, len(seq), size)
    )

In [ ]:
def custom_agg(
    sub_df: pd.DataFrame
) -> List[int | float]:
    """
    Performs custom aggregation for a sub-dataframe, ensuring output is JSON serializable.
    """
    aggregated_list = [
        float(sub_df['age'].mean()),
        int(sub_df['model2'].max()),
        int(sub_df['model3'].max()),
        int(sub_df['model4'].max()),
        float(sub_df['volt'].mean()),
        float(sub_df['volt'].std(ddof = 0)),  # ddof=0 for population std, ensuring result not NaN
        float(sub_df['rotate'].mean()),
        float(sub_df['rotate'].std(ddof = 0)),
        float(sub_df['pressure'].mean()),
        float(sub_df['pressure'].std(ddof = 0)),
        float(sub_df['vibration'].mean()),
        float(sub_df['vibration'].std(ddof = 0)),
        int(sub_df['comp1_maint'].sum()),
        int(sub_df['comp2_maint'].sum()),
        int(sub_df['comp3_maint'].sum()),
        int(sub_df['comp4_maint'].sum()),
        int(sub_df['error1'].sum()),
        int(sub_df['error2'].sum()),
        int(sub_df['error3'].sum()),
        int(sub_df['error4'].sum()),
        int(sub_df['error5'].sum()),
        int(sub_df['comp1_failure'].sum()),
        int(sub_df['comp2_failure'].sum()),
        int(sub_df['comp3_failure'].sum()),
        int(sub_df['comp4_failure'].sum()),
    ]
    # replace NaNs with zeros, assuming missing data can be treated as zero
    aggregated_list = [
        0 if np.isnan(x) else x for x in aggregated_list
    ]
    return aggregated_list

In [ ]:
def generate_features_dict(
    df: pd.DataFrame,
    hour_feature_window: int,
    chunk_size: int = 1
) -> Dict[
    str,
    List[List[Union[int, float]]]
]:
    """
    Generates a dictionary of features from the DataFrame based on chunk size.
    """
    assert hour_feature_window % chunk_size == 0, \
        f"chunk_size ({chunk_size}) must evenly divide hour_feature_window ({hour_feature_window})."

    # obtain column names to use for this hour_feature_window
    machineID_time_window_col = f'{hour_feature_window}_machineID_time_window'
    order_in_time_window_col = f'{hour_feature_window}_order_in_time_window'
    machine_example_ID_col = f'{hour_feature_window}_machine_example_ID'
    step_ID_col	= f'{hour_feature_window}_step_ID'

    # sort DataFrame
    df.sort_values(
        by = [machine_example_ID_col, order_in_time_window_col],
        inplace = True
    )

    # create features_dict
    features_dict = dict()
    for machine_example_ID, group in df.groupby(machine_example_ID_col):

        # process in chunks
        aggregated_data_list = [
            custom_agg(
                sub_df = group.iloc[chunk_indices]
            ) for chunk_indices in chunker(
                seq = range(group.shape[0]),
                size = chunk_size
            )
        ]
        #assert len(aggregated_data_list) == hour_feature_window / chunk_size, \
        #    f"len(aggregated_data_list) = {len(aggregated_data_list)}. Should be {hour_feature_window / chunk_size}! \n {aggregated_data_list}"


        # store data
        features_dict[machine_example_ID] = aggregated_data_list

    return features_dict

##### 1.2) Use Helper Function in Loop of Hour Windows

In [ ]:
for hour_feature_window in [12, 24, 48, 72]:
    print(f"- Hour Feature Window: {hour_feature_window}")

    # obtain features_dict
    features_dict = generate_features_dict(
        df = df,
        hour_feature_window = hour_feature_window,
        chunk_size = 1
    )
    print(f"\t- {format(len(features_dict), ',')} total rows in features_dict.")

    # remove last time interval (because there will be no corresponding outcome)
    machineID_time_window_col = f'{hour_feature_window}_machineID_time_window'
    max_machineID_time_window = df[machineID_time_window_col].max()
    max_machineID_time_window = f'{max_machineID_time_window:03}'
    features_dict = {
        k: v for k, v in features_dict.items()
        if str(k[6:9]) != max_machineID_time_window
    }
    print(f"\t- Removed max order in time window ({max_machineID_time_window}).")

    # print length of features_dict
    print(f"\t- {format(len(features_dict), ',')} total rows in features_dict.")

    # save as JSON
    SAVE_FILENAME = f'features_dict_{hour_feature_window}hrfeaturewindow.json'
    SAVE_LOC = os.path.join(SAVE_DATA_DIR, SAVE_FILENAME)
    with open(SAVE_LOC, mode = 'w') as json_f:
      json.dump(obj = features_dict, fp = json_f, indent = 4)
    print(f"\t- Saved file: {SAVE_FILENAME}")

- Hour Feature Window: 12
	- 73,100 total rows in features_dict.
	- Removed max order in time window (731).
	- 73,000 total rows in features_dict.
	- Saved file: features_dict_12hrfeaturewindow.json
- Hour Feature Window: 24
	- 36,600 total rows in features_dict.
	- Removed max order in time window (366).
	- 36,500 total rows in features_dict.
	- Saved file: features_dict_24hrfeaturewindow.json
- Hour Feature Window: 48
	- 18,300 total rows in features_dict.
	- Removed max order in time window (183).
	- 18,200 total rows in features_dict.
	- Saved file: features_dict_48hrfeaturewindow.json
- Hour Feature Window: 72
	- 12,200 total rows in features_dict.
	- Removed max order in time window (122).
	- 12,100 total rows in features_dict.
	- Saved file: features_dict_72hrfeaturewindow.json

In [ ]:
i = 0
for k, v in features_dict.items():
    i += 1
    if i > 1:
        break
    print(f"{k} -> {v}")
    print(len(v))

(001, 001) -> [[18.0, 0, 1, 0, 176.217853015625, 0.0, 418.504078221616, 0.0, 113.077935462083, 0.0, 45.0876857639276, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 162.87922289706, 0.0, 402.747489565395, 0.0, 95.4605253823187, 0.0, 43.4139726834815, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 170.989902405567, 0.0, 527.349825452291, 0.0, 75.2379048586662, 0.0, 34.1788471214451, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 162.462833264092, 0.0, 346.149335043074, 0.0, 109.248561276504, 0.0, 41.1221440884256, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 157.61002119306, 0.0, 435.376873016938, 0.0, 111.886648210168, 0.0, 25.9905109982024, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 172.504839196295, 0.0, 430.323362106675, 0.0, 95.9270416939636, 0.0, 35.6550173268837, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 156.556030606329, 0.0, 499.071623068962, 0.0, 111.755684290096, 0.0, 42.7539196974773, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 172.522780814836, 0.0, 409.624717000438, 0.0, 101.00108276407, 0.0, 35.4820086610704, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 175.324523915223, 0.0, 398.648780707752, 0.0, 110.624360548654, 0.0, 45.4822868466294, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 169.218423246933, 0.0, 460.850669930244, 0.0, 104.848229967003, 0.0, 39.9017354356787, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 167.060980719256, 0.0, 382.483542906686, 0.0, 103.780662505568, 0.0, 42.6757999060571, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 160.263953725914, 0.0, 448.084255968416, 0.0, 96.4809756730127, 0.0, 38.5436809273919, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 153.353491529019, 0.0, 490.672921027229, 0.0, 86.0124402476987, 0.0, 44.1085543746712, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 182.739113039826, 0.0, 418.199251966527, 0.0, 93.4849540613739, 0.0, 41.3671897268129, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 170.33543789114, 0.0, 402.461186552994, 0.0, 93.2357870560117, 0.0, 39.7398826787247, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 182.467109259603, 0.0, 501.918972726944, 0.0, 85.7626146951866, 0.0, 51.0214861151087, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 151.335682229837, 0.0, 444.922656455828, 0.0, 94.2473713287117, 0.0, 42.1196520943364, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 172.535396206493, 0.0, 511.886364263088, 0.0, 91.3294290707084, 0.0, 32.2488323711174, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 180.097494604215, 0.0, 486.712303934437, 0.0, 96.7339151541194, 0.0, 38.8967757315964, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 169.605854353272, 0.0, 519.452812074631, 0.0, 78.8807795743296, 0.0, 40.1568749074533, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 167.12911747166, 0.0, 427.050768115584, 0.0, 91.699898772144, 0.0, 44.6423514036463, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 158.271400299502, 0.0, 422.811051731942, 0.0, 92.439131917866, 0.0, 39.7819170940945, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 200.872429816452, 0.0, 403.235950789794, 0.0, 96.5354865291898, 0.0, 32.516837643016, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 181.257521797337, 0.0, 495.777957815984, 0.0, 93.4392900485745, 0.0, 52.3558761423939, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 197.363124535674, 0.0, 446.943947291323, 0.0, 114.342060814369, 0.0, 29.5276645184185, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 171.20089461638, 0.0, 384.645961639767, 0.0, 103.373293274323, 0.0, 35.79656613695, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 160.528860515505, 0.0, 486.459056124098, 0.0, 86.9442726860067, 0.0, 42.9925094428893, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 147.300678199494, 0.0, 420.610791774935, 0.0, 110.40898468439, 0.0, 34.203042245766, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 160.458502533724, 0.0, 412.965695619609, 0.0, 90.7113544990198, 0.0, 36.9637662572932, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 173.394522987457, 0.0, 439.579459789252, 0.0, 97.6758268612381, 0.0, 37.1171025574271, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 185.205355211986, 0.0, 445.606446690412, 0.0, 105.993246631457, 0.0, 47.8624842432991, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 173.791252025995, 0.0, 385.354923836333, 0.0, 99.5068188291068, 0.0, 42.921336262961, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 152.420775307383, 0.0, 497.840620071239, 0.0, 101.641691473293, 0.0, 30.6651841402327, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 180.030714927875, 0.0, 486.893593050412, 0.0, 93.7438265959588, 0.0, 43.0997584397585, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 145.248485977335, 0.0, 495.37644917672, 0.0, 111.950587257381, 0.0, 37.4222721271902, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 164.512216277121, 0.0, 424.542632589677, 0.0, 102.485529812427, 0.0, 42.2433743345421, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 165.258225067504, 0.0, 493.161428499927, 0.0, 127.014497747491, 0.0, 45.135193969702, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 140.776309290179, 0.0, 432.043773280403, 0.0, 99.8244970061128, 0.0, 31.2793209059224, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 183.800862835864, 0.0, 414.274295077659, 0.0, 86.3237598911335, 0.0, 37.7898336790742, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 160.656926076817, 0.0, 446.613842636735, 0.0, 115.31331185493, 0.0, 35.9445640032966, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 164.989450250038, 0.0, 418.069791413792, 0.0, 80.6682867298282, 0.0, 42.6386786957738, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 190.927218387944, 0.0, 437.960441292353, 0.0, 85.2602473493877, 0.0, 40.566201816709, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 179.550116165584, 0.0, 502.78745627213, 0.0, 109.966020203034, 0.0, 41.7306976683389, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 168.373524545144, 0.0, 489.910897754736, 0.0, 114.042406182779, 0.0, 36.0926564186992, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 177.70644167607, 0.0, 521.837936384375, 0.0, 101.528033099946, 0.0, 35.4684440422458, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 175.989077109109, 0.0, 510.256976083485, 0.0, 92.3628724738384, 0.0, 36.3760336560555, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 194.942846711456, 0.0, 418.84227125567, 0.0, 95.8963122269502, 0.0, 47.1636484547546, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 174.138401053782, 0.0, 489.250315154368, 0.0, 91.9263060883607, 0.0, 32.3236161048206, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 177.594089348115, 0.0, 459.95666980843, 0.0, 96.6516244215867, 0.0, 52.9973268810933, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 175.213279625357, 0.0, 486.494803791468, 0.0, 104.432962165098, 0.0, 47.8758037241602, 0.0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 164.341435287555, 0.0, 568.972310325907, 0.0, 94.4885331488906, 0.0, 49.0235846106559, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 171.464291946639, 0.0, 454.317958809318, 0.0, 85.2466095100028, 0.0, 47.6984635458459, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 194.581169676826, 0.0, 448.360259073022, 0.0, 98.3906177103568, 0.0, 50.60214119013, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 156.866112887156, 0.0, 405.869840207545, 0.0, 98.6408163025054, 0.0, 54.6981626190991, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 171.826399979616, 0.0, 439.841488841884, 0.0, 87.8748712529239, 0.0, 55.7680965643237, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 190.431959912675, 0.0, 427.675887842419, 0.0, 116.008404147721, 0.0, 55.062110464248, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 166.480683696159, 0.0, 487.422676443205, 0.0, 90.423891865119, 0.0, 66.7645147253914, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 154.199257880854, 0.0, 469.854312624191, 0.0, 85.7555462286093, 0.0, 47.9467927154542, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 156.953245915461, 0.0, 462.024181733621, 0.0, 106.346717905804, 0.0, 48.8203008633275, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 164.148094555294, 0.0, 429.822143515459, 0.0, 104.532123632465, 0.0, 43.7886815487723, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 157.289748903056, 0.0, 416.035004146499, 0.0, 93.1069855553634, 0.0, 48.4143591152758, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 166.090409118509, 0.0, 425.803431330431, 0.0, 87.6854178505576, 0.0, 57.9280573532398, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 163.783704404872, 0.0, 520.582694406777, 0.0, 97.1609838936527, 0.0, 56.4424877315265, 0.0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 167.254238034208, 0.0, 382.541315010965, 0.0, 104.485227039213, 0.0, 39.2735674729836, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 176.105841468209, 0.0, 428.325821832027, 0.0, 107.266871515655, 0.0, 52.3646754722338, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 179.369496923032, 0.0, 374.127148089674, 0.0, 87.7374352276446, 0.0, 49.1539724554269, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 195.173086155571, 0.0, 436.173620108302, 0.0, 103.833238374841, 0.0, 49.9471020513049, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 168.969595196525, 0.0, 467.285904563915, 0.0, 117.148227346375, 0.0, 58.3920501669205, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 165.187401310127, 0.0, 475.126936759955, 0.0, 114.584420977964, 0.0, 57.5490157337645, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 192.065085755734, 0.0, 506.595128588594, 0.0, 113.672300622123, 0.0, 57.8091616632702, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 195.564940967406, 0.0, 384.138904796328, 0.0, 106.552827821944, 0.0, 49.6573916294828, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [18.0, 0, 1, 0, 170.648660563363, 0.0, 464.189725862304, 0.0, 103.742947362501, 0.0, 58.4576673377802, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
72